version: '3.1'
services:
 db:
  image: postgres:10.3
  volumes:
   - dbdata:/var/lib/postgresql/data
   - ./../db/schema.sql:/var/schema.sql
   - ./../db/init.sh:/docker-entrypoint-initdb.d/init.sh
  ports:
   - 15432:5432
  env_file: .env
  networks:
   - xnet
 adm:
  image: adminer
  ports:
   - 8081:8080
  networks:
   - xnet
  depends_on:
   - db
 app:
  #image: python:3.6-stretch
  image: bubbles_python:2
  ports:
   - 58000:58000
  volumes:
   - ./../app:/app
  env_file: .env
  networks:
   - xnet
  depends_on:
    - adm
  command: [python, '/app/main.py']
 web:
  image: nginx:1.13
  volumes:
   - ./../adm:/adm
   - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - 8080:80
  environment:
   - NGINX_HOST=foobar.com
   - NGINX_PORT=80
  networks:
   - xnet
  depends_on:
    - app
  command: [nginx, '-g', 'daemon off;']
networks:
 xnet:
volumes:
 dbdata: